version: "1.0"
info:
  model: int-scaffold
packages:
- name: RajniGitproject0602Project
  gitServerName: KusiVCGithub
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
